set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CRT_LINKAGE dynamic)

set(VCPKG_LIBRARY_LINKAGE static)
if(PORT MATCHES "openssl" OR PORT MATCHES "qt5-" OR PORT MATCHES "libpq" OR PORT MATCHES "boost-" OR PORT MATCHES "grpc" OR PORT MATCHES "fftw3" OR PORT MATCHES "openblas" OR PORT MATCHES "curl" OR PORT MATCHES "freetype" OR PORT MATCHES "hdf5" OR PORT MATCHES "opus" OR PORT MATCHES "ffmpeg" OR PORT MATCHES "libwebp" OR PORT MATCHES "icu" OR PORT MATCHES "harfbuzz" OR PORT MATCHES "python")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

